#include QMK_KEYBOARD_H

// Helpful defines
#define _______ KC_TRNS

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_5x15(KC_1, KC_2, KC_3, KC_4, KC_5, KC_ESC, KC_BSPC, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_NO, KC_NO, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_LBRC, KC_RBRC, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_NO, KC_NO, KC_NO, KC_A, KC_S, KC_D, KC_F, KC_G, KC_TAB, KC_DOT, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_NO, KC_NO, KC_NO, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_NO, KC_NO, KC_N, KC_M, KC_COMM, KC_UP, KC_SLSH, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_LALT, KC_LGUI, KC_SPC, MO(1), KC_LSFT, KC_LSFT, MO(1), KC_ENT, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_NO),
	[1] = LAYOUT_ortho_5x15(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_PWR, KC_DEL, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_NO, KC_NO, KC_NO, KC_F11, KC_F12, KC_NO, KC_SLCK, KC_LGUI, KC_MRWD, KC_MFFD, KC_JYEN, KC_NO, KC_NO, KC_NO, KC_MPLY, KC_NO, KC_NO, KC_NO, KC_F4, LCTL(LSFT(LGUI(KC_4))), KC_F11, LCTL(LGUI(KC_F)), KC_GRV, KC_CAPS, RESET, KC_MINS, KC_EQL, KC_QUOT, LCTL(LGUI(KC_Q)), KC_NO, KC_NO, KC_NO, KC_NO, LGUI(KC_Z), LGUI(KC_X), LGUI(KC_C), LGUI(KC_V), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PGUP, KC_BSLS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_PGDN, KC_END, KC_NO, KC_NO, KC_NO)
};
